### ISSUE TITLE
popweb crash on macos

### ISSUE THREAD

**Issue by bbenchen** [manateelazycat/popweb#43]
Traceback (most recent call last):
  File "/Users/chenxianbin/.emacs.d/.local/straight/build-28.2/popweb/popweb.py", line 67, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/chenxianbin/.emacs.d/.local/straight/build-28.2/popweb/popweb.py", line 423, in hide_web_window
    web_window.developer_tools_view.hide()
AttributeError: 'WebWindow' object has no attribute 'developer_tools_view'

**Comment by bbenchen** [comment]
popweb-enable-developer-tools 的值为 nil

**Comment by manateelazycat** [comment]
更新看看？

**Comment by bbenchen** [comment]
@manateelazycat 没有问题了，thanks
