### ISSUE TITLE
popweb has an error with EPC

### ISSUE THREAD

**Issue by BossCode45** [manateelazycat/popweb#55]
Whenever I try to use the url preview nothing happens and this error appears in the popweb buffer
```
ERROR:epc:AttributeError("'Symbol' object has no attribute 'value'")
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "/home/boss/.local/lib/python3.10/site-packages/epc/handler.py", line 238, in _handle
    (name, uid, args) = unpack_message(sexp)
  File "/home/boss/.local/lib/python3.10/site-packages/epc/handler.py", line 87, in unpack_message
    return (data[0].value(), data[1], data[2:])
AttributeError: 'Symbol' object has no attribute 'value'
ERROR:epc:AttributeError("'Symbol' object has no attribute 'value'")
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "/home/boss/.local/lib/python3.10/site-packages/epc/handler.py", line 238, in _handle
    (name, uid, args) = unpack_message(sexp)
  File "/home/boss/.local/lib/python3.10/site-packages/epc/handler.py", line 87, in unpack_message
    return (data[0].value(), data[1], data[2:])
AttributeError: 'Symbol' object has no attribute 'value'
ERROR:epc:AttributeError("'Symbol' object has no attribute 'value'")
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "/home/boss/.local/lib/python3.10/site-packages/epc/handler.py", line 238, in _handle
    (name, uid, args) = unpack_message(sexp)
  File "/home/boss/.local/lib/python3.10/site-packages/epc/handler.py", line 87, in unpack_message
    return (data[0].value(), data[1], data[2:])
AttributeError: 'Symbol' object has no attribute 'value'
ERROR:epc:AttributeError("'Symbol' object has no attribute 'value'")
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "/home/boss/.local/lib/python3.10/site-packages/epc/handler.py", line 238, in _handle
    (name, uid, args) = unpack_message(sexp)
  File "/home/boss/.local/lib/python3.10/site-packages/epc/handler.py", line 87, in unpack_message
    return (data[0].value(), data[1], data[2:])
AttributeError: 'Symbol' object has no attribute 'value'
```
I installed all the python packages like it says on the install guide.

**Comment by manateelazycat** [comment]
Please use `pip3 install sexpdata==0.0.3` install sexpdata 0.0.3 to fix this problem.
